In [103]:
import time      # for testing use only
import os         # for testing use only

import bs4
import requests
from bs4 import BeautifulSoup  
import pandas as pd
import scipy as sc
import numpy as np

In [104]:
homepage = 'https://www.ad.co.il'
page1= requests.get(homepage + '/nadlansale/')
soup = BeautifulSoup(page1.text, 'html.parser')

In [105]:
def check_if_exist(lenth):
    if (lenth == 3):
         exist = 1 #not exist
    else:
        exist = 0 #exist
    return exist

In [121]:
type_house=[] #סוג הנכס
city=[] # עיר
street=[] #רחוב
prices=[] #מחיר
num_of_rooms=[] #מספר חדרים
floors=[] #קומה
elevator=[] #מעלית
furniture=[] #רהיטים
bars=[] #סורגים
terrace=[] #מרפסת
parking=[] #יש חניה או אין
size_per_mm =[] #גודל הדירה במ"מ
n_pages =1869
main_data =soup.find_all('div',attrs={'class':'card overflow-hidden'})
numberPage = 1
    for lst in main_data:
        all_apartment_pages= lst.find('a')
        html_doc = homepage + all_apartment_pages.get("href")
        apartment_page = requests.get(html_doc)
        details_soup = BeautifulSoup(apartment_page.text, "html.parser")
        details_Block = details_soup.find('div',attrs={'class':'single-product-tab tab-pane fade show active'})  
        price = details_Block.find_all('h2', attrs={'class':'card-title'})
        floor = details_Block.find_all('span', attrs={'class':'ms-1'})
        details_Block2=details_soup.find('table',attrs={'class':'table table-sm mb-4'})
        tabel_details = details_Block2.find_all('td')
        last_block = details_soup.find('div',attrs={'class':'card-icons flex-wrap d-flex h-100'})
        last_block_details = last_block.find_all('div')
        print(tabel_details[5].get_text())
        print(tabel_details[9].get_text())
        if(len(price) == 2 and len(floor) == 3):
            prices.append(price[1].get_text())
            floors.append(floor[2].get_text())
            num_of_rooms.append(floor[0].get_text())
            size_per_mm.append(floor[1].get_text())
            type_house.append(tabel_details[1].get_text())
            city.append(tabel_details[5].get_text())
            street.append(tabel_details[9].get_text())
            furniture.append(check_if_exist((len(last_block_details[1].get('class')))))
            parking.append(check_if_exist(len(last_block_details[3].get('class'))))
            terrace.append(check_if_exist(len(last_block_details[5].get('class'))))
            bars.append(check_if_exist(len(last_block_details[7].get('class'))))
            elevator.append(check_if_exist(len(last_block_details[8].get('class'))))
    end_block = soup.find('li', attrs={'class':'page-item mx-1 nextPage'})
    next_p = end_block.find('a', attrs={'class':'page-link'} )
    html_dock_new = homepage + next_p.get("href")
    n_page= requests.get(html_dock_new)
    soup = BeautifulSoup(n_page.text, "html.parser")
    numberPage = numberPage + 1
    main_data = soup.find_all('div',attrs={'class':'card overflow-hidden'})
df=pd.DataFrame({'Type house': type_house ,  'City': city, 'Street':street, 'Num of rooms': num_of_rooms ,  'Floor': floors,
                 'Price':prices,  'Bars': bars,  'Furniture': furniture,  'Elevator': elevator,  'Terrace': terrace
                ,  'Parking': parking,  'Size of house per mm': size_per_mm})
df

1

                    תל אביב יפו


                    4


                    אילת


                    5


                    חוסן


                    330


                    מזכרת בתיה


                    4


                    ירושלים


                    עמנואל זיסמן 31


                    ירושלים


                    3


                    חדרה


                    הגפן 14


                    רעננה


                    1


                    פתח תקווה


                    ביל"ו 10


                    לוד


                    שפרינצק


                    קרית ביאליק


                    חיים


                    הרצליה


                    3


                    תל אביב יפו


                    בושם 64


                    ירושלים


                    פרץ ברנשטיין


                    באר שבע


                    נחום שריג


                    יבנאל


                    1


                    באר שבע


                    רבי עקיבא


                    רחובות


                    קרקע מתוך קרקע


                    חולון


                    צפת


                    ירושלים


                    4


                    הרצליה


                    בורוכוב


                    קיסריה


                    3


                    תל אביב יפו


                    6


                    גני תקווה


                    התבור 6


                    קרית טבעון


                    600


                    גבעת שמואל


                    5


                    תל אביב יפו


                    טאגור


                    רמת גן


                    אביגיל 6


                    נתניה


                    אוסישקין 24


                    פתח תקווה


                    ליברמן


                    גבעתיים


                    5


                    נהריה


                    הרצל


                    אור עקיבא


                    השיקמים


                    רחובות


                    זאב יעבץ


                    תל אביב יפו


                    5


                    תל אביב יפו


                    יוסף זימן


                    תל אביב יפו


                    4


                    נהריה


                    אחד העם 16


                    אודים


                    7960


                    עתלית


                    534


                    רמת גן


                    הזיתים


                    רמלה


                    משה לוי 1


                    ירושלים


                    פרנס


                    טירת כרמל


                    דולפין


                    באר שבע


                    דרך מצדה


                    גבעת שמואל


                    יוני נתניהו


                    אשדוד


                    דקר


                    תל אביב יפו


                    הרב ניסים


                    רמת גן


                    קריניצי

AttributeError: 'NoneType' object has no attribute 'find_all'

In [114]:
df=pd.DataFrame({'Type house': type_house ,  'City': city, 'Street':street, 'Num of rooms': num_of_rooms ,  'Floor': floors,
                 'Price':prices,  'Bars': bars,  'Furniture': furniture,  'Elevator': elevator,  'Terrace': terrace
                ,  'Parking': parking,  'Size of house per mm': size_per_mm})
df

,Type house,City,Street,Num of rooms,Floor,Price,Bars,Furniture,Elevator,Terrace,Parking,Size of house per mm
0,\r\n דירה\r\n,\r\n יהוד מונוסון\r\n ...,\r\n 1\r\n,5 חד',קומה 8,"2,550,000 ₪",0,0,1,1,1,"128 מ""ר"
1,\r\n בית פרטי/קוטג'\r\n ...,\r\n באר שבע\r\n ...,\r\n בצלאל 49\r\n ...,5 חד',קרקע,"1,600,000 ₪",1,1,0,0,1,"120 מ""ר"
2,\r\n דירה\r\n,\r\n קרית גת\r\n ...,\r\n 2 מתוך 3\r\n ...,3.5 חד',קומה 2,"870,000 ₪",0,0,0,0,0,"87 מ""ר"
3,\r\n דירה\r\n,\r\n מודיעין מכבים רעות\r\n...,\r\n כסלו 5\r\n ...,5 חד',קומה 2,"2,590,000 ₪",0,0,1,1,1,"160 מ""ר"
4,\r\n דירה\r\n,\r\n קרית ים\r\n ...,\r\n תבור\r\n,3 חד',קומה 8,"760,000 ₪",1,0,1,0,0,"69 מ""ר"
...,...,...,...,...,...,...,...,...,...,...,...,...
52320,\r\n דירה\r\n,\r\n באר שבע\r\n ...,\r\n דרך מצדה\r\n ...,3.5 חד',קומה 2,"730,000 ₪",1,1,0,0,0,"76 מ""ר"
52321,\r\n דירה\r\n,\r\n גבעת שמואל\r\n ...,\r\n יוני נתניהו\r\n ...,6 חד',קומה 4,"3,700,000 ₪",1,0,1,1,1,"170 מ""ר"
52322,\r\n פרטי/קוטג'\r\n ...,\r\n אשדוד\r\n,\r\n דקר\r\n,7 חד',קרקע,"5,300,000 ₪",0,0,0,0,0,"600 מ""ר"
52323,\r\n דירה\r\n,\r\n תל אביב יפו\r\n ...,\r\n הרב ניסים\r\n ...,4.5 חד',קומה 18,"8,600,000 ₪",0,1,1,1,1,"153 מ""ר"
52324,\r\n דירה\r\n,\r\n רמת גן\r\n ...,\r\n קריניצי\r\n ...,3.5 חד',קרקע,"4,500 ₪",1,1,0,0,0,"67 מ""ר"

In [115]:
df.to_csv("apartment data ad website.csv" ,encoding = 'utf-8-sig')